version: "3.6"

services:
  demo-app:
    image: integration-testing:1.0
    container_name: "demo-app"
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: "8080"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://demo-postgres:5432/demo-db"
      SPRING_DATASOURCE_USERNAME: "demo-user"
      SPRING_DATASOURCE_PASSWORD: "demo-password"
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "500"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - demo-postgres

  demo-postgres:
    container_name: "demo-postgres"
    image: "postgres:12.4-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "demo-user"
      POSTGRES_PASSWORD: "demo-password"
      POSTGRES_DB: "demo-db"